// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi2EFhVaQ1OEsbAfn6mvcqEzWo_wcTiP4',
    appId: '1:27826887390:web:0c4f4764ddebe52076804f',
    messagingSenderId: '27826887390',
    projectId: 'tdstores-59c52',
    authDomain: 'tdstores-59c52.firebaseapp.com',
    storageBucket: 'tdstores-59c52.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWZ2kzElWJ-foTNc6GsC98MSAO9ASZap0',
    appId: '1:27826887390:android:4c382ecd6677bf3076804f',
    messagingSenderId: '27826887390',
    projectId: 'tdstores-59c52',
    storageBucket: 'tdstores-59c52.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHj3nzg2hh-ouLOioKHSijt2n9lCnJKhY',
    appId: '1:27826887390:ios:f40dc3c6c0fcdd9676804f',
    messagingSenderId: '27826887390',
    projectId: 'tdstores-59c52',
    storageBucket: 'tdstores-59c52.firebasestorage.app',
    androidClientId: '27826887390-2k75psatpb3r3unmh9nehjk83chn6l5t.apps.googleusercontent.com',
    iosClientId: '27826887390-nper99o0rair458quvc4somscbu3utk7.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );
}
